# Generated by Django 3.2.9 on 2021-11-26 13:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sure',
            name='pub_date',
        ),
    ]
